# Generated by Django 4.1.2 on 2022-10-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('Tempid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
