# Generated by Django 4.1.2 on 2022-10-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookings',
            field=models.ManyToManyField(through='restapi.Booking', to='restapi.hall'),
        ),
    ]
