# Generated by Django 4.1.2 on 2022-10-25 05:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_name', models.CharField(max_length=40)),
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_mail', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked', models.BooleanField()),
                ('pending', models.BooleanField()),
                ('slotStart', models.DateTimeField(blank=True, null=True)),
                ('slotEnd', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_name', models.CharField(max_length=40)),
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('hall_location', models.CharField(max_length=40)),
                ('hall_capacity', models.IntegerField()),
                ('hall_rating', models.IntegerField()),
                ('hall_image', models.CharField(max_length=40)),
                ('hall_selectedslots', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_approved', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='TempModel',
        ),
        migrations.AddField(
            model_name='datetime',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.hall'),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_booked',
            field=models.ManyToManyField(through='restapi.DateTime', to='restapi.hall'),
        ),
    ]
